/// Patient data model.
///
/// In production deployments this model carries only the **de-identified**
/// representation of the patient (subject code + demographics). The real
/// name, identity card and phone are stored server-side in the encrypted
/// `PatientIdentityMap` and only returned to the dedicated identity API
/// for users with role `PI` / `Admin`. See `GCP合规要求_老胡参考.md` and
/// `差距清单与落地建议.md` §11 for the rationale.
///
/// The `name` field is preserved in the demo backend so the seeded data
/// is realistic, but it is marked deprecated and **must not** be displayed
/// in any UI surface — use `displayLabel` instead.
class Patient {
  final String id;
  final String facilityId;

  /// GCP subject identification code. Primary patient identifier on every
  /// screen, report and CRF. Generated by `SubjectCodeGenerator`.
  final String subjectCode;

  /// Non-identifying code carried for backward compatibility with the
  /// existing demo data (`P-001` / `P-002` etc.). Will be removed once the
  /// demo dataset is re-seeded.
  @Deprecated('Use subjectCode instead — see SubjectCodeGenerator')
  final String patientCode;

  /// **Deprecated in production.** Demo-only field that carries the real
  /// name. UI must never display this — use `displayLabel` instead.
  @Deprecated('Real name is server-side only. Use displayLabel for UI.')
  final String? name;

  /// True iff the current session has permission to see the real name.
  /// The mobile UI consults this flag before rendering any header that
  /// could leak PHI.
  final bool canViewRealName;

  /// Server-side identifier for the encrypted identity record. The mobile
  /// client uses this to fetch the real name through the dedicated API.
  final String? identityRecordId;

  final String? medicalRecordNo;
  final DateTime? dateOfBirth;
  final String? gender;
  final String? protocolId;
  final String? centerId;
  final String? consentId;
  final DateTime? enrollmentDate;
  final DateTime createdAt;
  final DateTime updatedAt;

  const Patient({
    required this.id,
    required this.facilityId,
    required this.subjectCode,
    @Deprecated('Use subjectCode instead — see SubjectCodeGenerator')
        this.patientCode = '',
    @Deprecated('Real name is server-side only. Use displayLabel for UI.')
        this.name,
    this.canViewRealName = false,
    this.identityRecordId,
    this.medicalRecordNo,
    this.dateOfBirth,
    this.gender,
    this.protocolId,
    this.centerId,
    this.consentId,
    this.enrollmentDate,
    required this.createdAt,
    required this.updatedAt,
  });

  factory Patient.fromJson(Map<String, dynamic> json) {
    return Patient(
      id: json['id'] as String,
      facilityId: json['facilityId'] as String? ?? '',
      subjectCode: json['subjectCode'] as String? ??
          json['patientCode'] as String? ??
          '',
      patientCode: json['patientCode'] as String? ?? '',
      name: json['name'] as String?,
      canViewRealName: json['canViewRealName'] as bool? ?? false,
      identityRecordId: json['identityRecordId'] as String?,
      medicalRecordNo: json['medicalRecordNo'] as String?,
      dateOfBirth: json['dateOfBirth'] != null
          ? DateTime.tryParse(json['dateOfBirth'] as String)
          : null,
      gender: json['gender'] as String?,
      protocolId: json['protocolId'] as String?,
      centerId: json['centerId'] as String?,
      consentId: json['consentId'] as String?,
      enrollmentDate: json['enrollmentDate'] != null
          ? DateTime.tryParse(json['enrollmentDate'] as String)
          : null,
      createdAt: DateTime.parse(json['createdAt'] as String),
      updatedAt: DateTime.parse(json['updatedAt'] as String),
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'facilityId': facilityId,
        'subjectCode': subjectCode,
        'patientCode': patientCode,
        'name': name,
        'canViewRealName': canViewRealName,
        'identityRecordId': identityRecordId,
        'medicalRecordNo': medicalRecordNo,
        'dateOfBirth': dateOfBirth?.toIso8601String(),
        'gender': gender,
        'protocolId': protocolId,
        'centerId': centerId,
        'consentId': consentId,
        'enrollmentDate': enrollmentDate?.toIso8601String(),
        'createdAt': createdAt.toIso8601String(),
        'updatedAt': updatedAt.toIso8601String(),
      };

  Patient copyWith({
    String? id,
    String? facilityId,
    String? subjectCode,
    String? medicalRecordNo,
    DateTime? dateOfBirth,
    String? gender,
    String? protocolId,
    String? centerId,
    String? consentId,
    DateTime? enrollmentDate,
    bool? canViewRealName,
    String? identityRecordId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return Patient(
      id: id ?? this.id,
      facilityId: facilityId ?? this.facilityId,
      subjectCode: subjectCode ?? this.subjectCode,
      patientCode: patientCode,
      name: name,
      medicalRecordNo: medicalRecordNo ?? this.medicalRecordNo,
      dateOfBirth: dateOfBirth ?? this.dateOfBirth,
      gender: gender ?? this.gender,
      protocolId: protocolId ?? this.protocolId,
      centerId: centerId ?? this.centerId,
      consentId: consentId ?? this.consentId,
      enrollmentDate: enrollmentDate ?? this.enrollmentDate,
      canViewRealName: canViewRealName ?? this.canViewRealName,
      identityRecordId: identityRecordId ?? this.identityRecordId,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  /// Display label for **every** UI surface. Never returns `name` —
  /// always the de-identified subject code, prefixed with 受试者 so it
  /// reads naturally in Chinese.
  String get displayLabel {
    if (subjectCode.isNotEmpty) return '受试者 $subjectCode';
    // ignore: deprecated_member_use_from_same_package
    if (patientCode.isNotEmpty) return '受试者 $patientCode';
    return '受试者 #$id';
  }

  /// Short label for tight UI spaces (chips, table rows).
  String get shortLabel {
    if (subjectCode.isNotEmpty) return subjectCode;
    // ignore: deprecated_member_use_from_same_package
    if (patientCode.isNotEmpty) return patientCode;
    return '#$id';
  }

  /// Compute age in years from `dateOfBirth`. Returns null if DOB unknown.
  int? get age {
    if (dateOfBirth == null) return null;
    final now = DateTime.now();
    var a = now.year - dateOfBirth!.year;
    final hadBirthday =
        (now.month > dateOfBirth!.month) ||
            (now.month == dateOfBirth!.month &&
                now.day >= dateOfBirth!.day);
    if (!hadBirthday) a -= 1;
    return a;
  }

  /// Whether the current session has the right to see the real name. UI
  /// surfaces can gate the "查看真实姓名" action on this.
  bool get hasIdentityAccess => canViewRealName || identityRecordId != null;
}